// In the previous chapter we saw that $rho$ sat low, inside the range of pooling regime. This does not mean that no signalling emerged; it means only that the token carries little information about a driver's hidden type. Which leaves a sharper question: did the agents signal at all, and if so, in what sense? Our answer, and the thread that runs through this chapter, is that weak type-associated signalling did emerge, in a sense the field's standard metrics are not built to detect: senders commit to a token pattern deliberately, receivers act on the token they observe, and the population comes to rely on the resulting token-behaviour coupling, enough that corrupting it raises collisions substantially. We read this as a convention of _use_, a shared regularity in how the token is emitted and read, rather than a convention of _meaning about type_, which is exactly what did not emerge.

The previous chapter left an odd pairing unresolved: a token that reveals almost nothing about a driver's type, yet whose disruption the population pays for dearly. This chapter reads that pairing through the game theory of signalling and convention.

Driving on a highway can be read as a coordination problem. In Lewis's terms @lewis1969convention[p.~24], it is a decision-making situation involving two or more agents whose interests mostly coincide and who can coordinate on at least two different equilibrium outcomes. Concretely, there are many mutually compatible ways to interleave traffic, such as who leads a merge and who holds a lane. Drivers only need to settle on one of them, since almost any consistent choice works, while a mismatch ends in a collision. It is worth noting that such a game is not pure coordination. Coordinating still leaves "who yields, who takes the gap, who leads the merge". The yielder loses time; the one who goes gains. So drivers agree they must coordinate but disagree which equilibrium they prefer. That is a mixed-motive game in the sense of @schelling1960strategy[p:p.~89]. Highway driving is thus coordination-dominant but not pure coordination, mixed-motive at the edges.

What a message is worth in such a game depends on what one takes a signal to be for, and here game theory offers two quite different accounts. In the first account, a signal reveals something private about the sender. This is the logic of costly signalling @spence1973job and of cheap talk @crawford1982strategic, and it is what the separation coefficient $rho$ measures. Our channel is not cheap talk in the strict sense. Emitting a token selects an execution profile, so it changes the sender's own kinematics, and therefore its payoff, whether or not any neighbour ever reads it. That places it closer to the costly-signalling side of the pair, and it is the reason the binding, rather than the symbol, turns out to be what matters. Judged this way, the agents barely communicate at all, since the token carries less than a tenth of a bit about a driver's hidden type. In the second account a signal need reveal nothing. Its only job is to let everyone settle on the same arbitrary convention out of the many that would serve equally well, in the sense of @lewis1969convention[p:pp.~16-24] and @schelling1960strategy[p:pp.~54-58].

A coordination problem is not solely solved by revealing private information; it is solved by everyone landing on the same rule. For that reason our results read more naturally on the side of the second account, even though the metrics the field reaches for by default assume the first. The token says almost nothing about a driver's hidden type, yet the whole population organises its driving around it. It is not a failed code, it is what a convention looks like when the game rewards agreement over disclosure.

It helps to be precise about what kind of convention this is. A token can carry two very different conventions. The first is a _convention of meaning_ about type, where a token comes to stand for cautious or assertive so that reading it tells you who the sender is. This is what $rho$ scores, and it is exactly what did not emerge. The second is a _convention of use_: a shared, self-consistent regularity in how the population emits the token and how receivers respond to it, whatever it reveals about type. It is this second convention that emerged. Senders commit to a token pattern deliberately (Speaker Consistency well above chance), and receivers act on the token they observe (non-zero decoding in every one of the twenty seeds). The population comes to rely on the resulting token-to-behaviour coupling, enough that corrupting it raises collisions by 65% to 86%. What emerged is a habit of use that coordinates driving, not a code that reveals type. We encourage readers to review example (1) Ship Flag Hoists and (2) The Trucker and The Driver (titles added by the authors) in @lewis1969convention[pp.~125-127, 129-130] for illustration of _convention of use_.

That the channel is a convention rather than a code shows first in how the token is used from one run to the next. @fig-sig-heatmap shows that, on average, both types place most of their weight on token 2 (assertive kinematic envelope) though the preference is weak. The per-seed breakdown in @fig-sig-heatmap-seed tells the fuller story: individual seeds settle on different token conventions, and among the well-performing seeds several distinct choices reach comparable return. Different seeds assign the tokens differently, cautious agents commit to token 0 in one seed and to token 1 in another, yet both drive equally well. Relabelling the tokens in one seed's solution and it behaves like another seed's. No single labelling is privileged because the task never implicitly specifies which integer should mean which type, only that whichever mapping a population settles on stays consistent. The sharply higher collision rate and lower mean return under _permute_, _desync_ and _randomise_ are what a mismatch in a coordination problem looks like: sender and receiver are operating on different conventions, and the outcome degrades accordingly.

#figure(
  placement: auto,
  image("../figures/signal_heatmaps_per_seed.png"),
  caption: [Signal heatmap by seed in the bimodal condition, sorted by descending
    mean return.],
)<fig-sig-heatmap-seed>


This also settles what it means to speak of a signal's meaning. As the experimenter we label each token with the driving profile it triggers, token 2 with the assertive envelope for instance, but that label records only the grounding we built in, the mechanical consequence of emitting the symbol. It is not the token's communicative meaning. What a token signifies as a signal is fixed by how the population comes to use it, and that is a matter of convention, not of our labelling. This is @lewis1969convention[ps:pp.~130-132] point about signalling systems: a signal has no intrinsic meaning; its meaning just is the sender-receiver regularity the population adopts. We supply the vocabulary and its physical consequences and the agents supply the semantics.

If the particular labelling is arbitrary, why should the token matter at all? The answer is that its value never lay in what it reveals. Across twenty seeds the token carries almost nothing about a driver's hidden type ($rho approx 0.09$, with not one seed reaching the separating threshold), yet the population organises its driving around it. Corrupting the token-to-behaviour binding lifts the collision rate by 65% to 86%. A signal can thus be informationally near-silent and still be load-bearing.
Why the population pooled at all is a question about learning rather than about payoffs. Nothing in the design forced it. With three tokens available and only two types to tell apart, a separating code was within reach and would have cost nothing to represent; the channel had more capacity than the task required. The agents settled on using the tokens in much the same way whatever their type anyway.

@skyrms2010signals studies this question for Lewis signalling games played by agents who learn by reinforcement rather than by computing equilibria. In the smallest such game the learning process converges on a signalling system with probability one @skyrms2010signals[p.~94]. That guarantee is fragile, though: enlarge the game, and a run can converge on a partial pooling outcome with positive probability. A population can then settle into pooling that no one would have chosen deliberately, with the early and essentially arbitrary reinforcements deciding which outcome it reaches. Pooling on this account is an attractor of the learning process, not a property of the game being played.

The setting in such game is different from us (Lewis signalling game with two states, two signals, two acts; simple Roth-Erev reinforcement learning @erev1998PredictingHowPeople @roth1995Learning), so we do not claim the theorems transfer. What carries over is the shape of the explanation, and it fits empirical results. Separation coefficient $rho$ rises early and then flattens (refer to @fig-rho-training) rather than climbing towards separation even though we specially added signal-entropy bonus to prevent that (see @training-procedure). Consequently, it looks like learning outcome rather than slow progress. Individual seeds land on different token conventions and stay there (refer to @fig-sig-heatmap-seed). Read this way the near-empty token is not evidence that the task had no use for an informative signal. It is what a population of learners can settle into even when an informative signal was there to be found.

If the token is doing coordinating work, one might expect removing it to hurt. @fig-corruption-controls points out it does not. A population that never had the channel crashes at $34.9%$ against the communicating population's $38.5%$, and returns $187.9$ against $201.4$. Neither difference is detectable at twenty seeds per condition (Mann-Whitney $U=203.0$, $p=0.946$ for collision rate; $U=265.0$, $p=0.081$ for return; refer to @tab-nosignal-mw). The channel looks, in this sense, optional to adopt: the population reaches much the same place with it, without it, or ignoring it.

What is not optional is the cost of disrupting the relationship once it exists. The same token whose presence is dispensable becomes costly to corrupt, as breaking the token-to-behaviour binding lifts collisions by 65% to 86% over baseline. We read this as consistent with the convention of use described above, where emitting a token and driving the matching envelope tend to go together and receivers appear to have learned to read one from the other. On that reading, corrupting the binding does not remove information, since the token carried almost none. Instead it injects incoherence: a driver whose token and manoeuvre disagree breaks a regularity other drivers appear to expect. That mismatch is plausibly, though not directly shown, what the others crash into. A casual analogy is a traffic light. When a light loses power and goes dark, drivers fall back to a safe default, treating it as an all-way stop and creeping through, so traffic slows but almost nobody crashes. When a light instead malfunctions and shows green in every direction at once, it is actively misinforming, and confident drivers pull into each other. A missing light is safe; a misinformative light is a disaster.

A signal can be a convention and be informative at the same time. The signalling token here ended up carrying so little about type that it is worth asking why. The interventions locate the answer in where the useful information already lives. Strip the token but leave the kinematics and receivers lose only a few percent; strip the kinematics but leave the token and return collapses to about a third of baseline. What a receiver needs is written in the motion, not in the symbol. Because the channel is grounded, a driver's type already shows in how it accelerates and holds its lane, so the token has little left to add.

Redundancy removes the incentive: a purely cooperative objective rewards outcomes, not informative symbols, and once the kinematics reveal type there is nothing to pay for encoding it again. This is close to the classic condition under which cheap talk stays uninformative @crawford1982strategic, though the parallel is loose, since our token is not costless: it commits the sender to an execution profile. The redundancy argument does not need that result to stand. It needs only that the kinematics already carry type and that nothing in the reward pays for encoding it a second time. In our experiments, agents still performed the task without communication, showing that a good policy was reachable without it. The listener therefore ignored the sender's messages, and consequently the speaker had no incentive to produce meaningful signals @eccles2019biases. On this reading the empty token is not a failure of the setup but the expected outcome of learning a signal no one is paid to make informative.

We cannot fully separate could-not from need-not, whether the agents were unable to find an informative code or simply had no reason to; but with type already legible in the kinematics, redundancy is the more persuasive reading. Our design deliberately gives no reward that would steer agents towards any particular way of emitting signals. It is possible that with such a reward the token could become more informative about an agent's type, but we leave that to future work.

A convention only communicates if the receivers actually read it, and they do. Freezing the scene and swapping only the received token moves a receiver's next action about four times as much as in the controls (refer to @fig-cde). The information-theoretic version of the same test puts the influence at roughly seven times control levels (refer to @fig-cic). Both measures are non-zero in every one of the twenty seeds, and they agree closely with each other across seeds. The decoding is soft rather than dramatic, but it is real and it is everywhere. Paired with Speaker Consistency score, it supplies both halves of @lowe2019pitfalls operational definition of communication, positive signalling and positive listening. The strength of that decoding is also decoupled from $rho$ and from Speaker Consistency: receivers condition on the token about equally whether or not it carries type information. This is the convention of use at work, positive signalling paired with positive listening, and it holds even where the revelation metric reads essentially zero.

Taken at face value, the passive numbers are unremarkable. $rho$ sits in the pooling regime, and CIC, though reliably above control levels, is small in absolute magnitude. A reader who stopped at the scoreboard would hastily conclude that these small numbers are not the result of communication. Yet the same channel, when its binding is broken, costs a 65-to-86% rise in collisions. The interventions disagree about how much the token matters, and they are right: the dependence is real and large, and the scores simply do not see it.

The reason is that the existing metrics are instruments of the information-theoretic tradition. Mutual information asks how much a signal tells us about a hidden state but it is silent about the load carried by a signal that reveals nothing yet binds an action others depend on. We mean binding here in the mechanical sense that emitting a token forces a matching execution profile. A convention of this kind is invisible to a passive audit and shows itself only under active perturbation. @lowe2019pitfalls and @eccles2019biases recommend exactly this: to certify that a channel is used, one must intervene on it and watch behaviour move. Our methodology and interventions offer a different perspective on emergent communication in multi-agent systems generally, and in multi-agent autonomous driving in particular: communication can occur not by being informative, but by establishing a behavioural convention.

These findings carry a practical reading for connected and autonomous driving. The lesson for a vehicle-to-vehicle protocol is that the quantity worth protecting is the binding between message and manoeuvre, not the mere presence of messages or their informational richness. A vehicle can broadcast an accurate self-report but act inconsistently with it. Because existing information metrics score only the honesty of what is said about type, not the coupling between message and behaviour, they can certify a channel that is in fact behaviourally unreliable. Evaluation of connected AVs should therefore test the message-to-manoeuvre binding directly, not just the informativeness of the messages. This is in line with  Vehicle-to-Everything (V2X) misbehaviour-detection and intent-recognition research that already looks for inconsistency between what a vehicle signals and how it drives. We advance this as an implication rather than a demonstration, since our evidence comes from a single simulated environment, but the direction it points is clear.


Several limitations bound these claims. First, the evidence comes from a single simulated environment at small scale, six agents on one straight highway with no background traffic. Whether the same regime holds under a different road layout, more agents, or scripted background traffic remains an open question. Second, the population mix is also held fixed at an even split. We ran only this balanced bimodal composition rather than a sweep over type proportions. It is therefore unknown how the emergent regime depends on the balance of cautious and assertive drivers, and whether a skewed population would push it toward or away from separation. The no-signal comparison also confounds two factors, since that condition removes the token and fixes the execution profile at neutral in the same step. Separating them would need a fifth condition in which agents keep the three profiles but select among them without emitting anything a neighbour can read. Fourth, the experiments are solely simulated under one scenario which is driving on the highway. Further experiments should be conducted under other scenarios such as merging, driving at a roundabout or an intersection. Finally, the mechanism identified here rests on kinematic cost asymmetries built into a simplified simulator; dynamics of simulation environment are not validated against real driving data, and it is unclear whether the same claims would survive real vehicle dynamics, sensor noise, and imperfect perception.
