Autonomous vehicles have gradually moved from test tracks onto public roads. Robotaxis have been carrying passengers in several cities, and driver-assistance systems have been deployed in commercial cars. More and more manufacturers are building these systems, and no two are alike. They run different sensors, different planners, and different driving policies, trained separately and opaque to one another. For a long time to come they will also share the road with human drivers rather than replace them, so any one car has to cope with mixed, heterogeneous traffic it neither controls nor can see inside. This makes how such vehicles communicate with each other important. But whether communication can emerge among these vehicles is still unsettled. This dissertation asks that question, in a small, controlled version of the problem.

Driving on a highway means constantly reacting to cars you cannot fully read. Whether a neighbour is cautious or assertive, how much risk they accept, how close they like to follow, none of this is visible directly. The usual approach in the field is perception, prediction, and planning: build a model of how nearby cars are likely to move, and plan around it @chen2022milestones. These prediction methods have improved a great deal, from simple rule-based simulation, to tracking a few possible intentions @bai2015intention @zhou2018joint, to learning a hidden driver type from data with neural-network encoders @liu2022learning @liu2024automatic @ma2021reinforcement.

But this whole line of work looks at only one side of the problem. The car asks "what will my neighbour do?" and stops there. A human driver also asks the other half: "what do our neighbours think I am, and is the way I drive shaping that belief?" How a driver acts matters as much as how it reads and responds to others, since that action is what lets other drivers form a belief about its type. Those interactions act as signals that help agents coordinate with each other @fox2018when @risto2017human @wang2020driver.

Take a simple two-car example. Car A is cautious and car B is assertive, and neither can see the other's type directly. The two approach a merge where only one can go first. B wants A to know that it will not back off, so it makes that intent legible in the only way available: it closes the gap quickly, holds a tight headway, and accelerates decisively towards the merge point. None of this is a message in any literal sense. It is simply how B drives, but executed firmly enough that the style itself announces an assertive type.

A reads that style, infers an assertive neighbour, and answers with its own: it eases off, opens the gap, and lets B take the space. That cautious response is itself legible to B, which now sees a driver willing to give way. The two settle without a collision and without any negotiation, as B goes first and A follows. Neither changed who it is. B stayed assertive and A stayed cautious; they did not meet in the middle on a shared style, but read each other's style and each kept its own, and that mutual reading let them coordinate. Neither car sent a message. The coordination came entirely from the visible manner of ordinary moves, where the same manoeuvre carries different information depending on _how_ it is executed.

// #figure(
//   image("../figures/two-car-example.png"),
//   caption: [Example illutration.],
// )

This is the setting studied by signalling-game theory @crawford1982strategic @spence1973job @lewis1969convention. An informed sender gives off a signal; an uninformed receiver reads it and updates what it believes. Outcomes fall into three cases: separating, where each type sends a different signal and the signal is fully informative; pooling, where every type sends the same signal and it tells you nothing; and partial-pooling in between @fudenberg1991game.

This thesis treats cooperative multi-agent highway driving as a signalling game and builds tools to determine which case actually appears when agents learn to use a shared set of discrete tokens whose meanings are left open. To keep every token tied to real behaviour, the signalling channel is grounded: sending a token forces the sender into a matching driving style. Moreover, we keep the agents cooperative on purpose. That way, if they end up pooling, it cannot be because someone is lying for an advantage, so the result tells us about the structure of the game rather than about clever deception.

Framing it this way also changes how we should judge success. Work on emergent communication in multi-agent systems (MAS) asks exactly this question of how agents learn to use a shared set of signals @foerster2016learning @sukhbaatar2016learning @lazaridou2020emergent. It usually measures success with information: a channel counts as communication if its messages tell you something about the sender's hidden state. That test assumes a signal exists to reveal private information @spence1973job @crawford1982strategic, and it is normally read off a trained model without touching it. But a message can align with a hidden state without the receiver ever using it @lowe2019pitfalls @eccles2019biases, and a channel whose real job is to coordinate behaviour, not to reveal type, can be invisible to such a test. In a safety-critical setting, a metric that cannot tell a useless channel from an important one is dangerous.

Concretely, we ask two research questions:
- *RQ1*: Does type-contingent signalling emerge at all, when cooperative agents share a grounded set of tokens whose meanings are left open?
- *RQ2*: Is any such emergence driven by type-dependent reward heterogeneity between the drivers, rather than by the presence of the signalling architecture itself?

We train groups of six agents with Multi-Agent Proximal Policy Optimisation (MAPPO) @yu2022surprising under four conditions, twenty seeds each, each isolating one factor. The _bimodal_ is the full model, with heterogeneous driver types and an intact channel. The _same-reward_ keeps the channel but gives both types identical rewards, removing the type-dependent reward heterogeneity. The _random-signal_ keeps that reward heterogeneity but replaces the emitted token with a random draw, severing type from signal, giving a baseline that any real emergence has to beat. The _no-signal_ removes the channel entirely, leaving only neighbour kinematics, as a plain kinematics-only baseline.

We run a set of interventions at evaluation time that separately disturb the token, the neighbour kinematics, and the link between them. We also introduce the Counterfactual Decoding Effect (CDE), a receiver-side measure that reads how much a receiver's action changes, in real control units, when only the token it receives is swapped. We report it alongside the information-based Causal Influence of Communication (CIC) @lowe2019pitfalls. Finally we read the results through the difference between signals that reveal private information and conventions that only coordinate.

This dissertation makes four contributions. First, it formally frames cooperative highway driving as a learned signalling game over a discrete, behaviour-grounded set of tokens with open meanings. It studies the emergent convention itself rather than only the driving policy it produces. Second, it shows that the channel carries almost no type information but that its integrity still matters. Breaking the link between token and behaviour raises the collision rate by 65% to 86%, depending on how the link is broken. At the same time, a population trained with no channel at all shows no detectable difference in collision rate or return. Third, it introduces the Counterfactual Decoding Effect, an action-space measure of decoding that agrees closely with the information-based measure across seeds. Fourth, it offers a caution for the method, drawn from what happened here rather than asserted in general. In this experiment, the active interventions exposed a dependence on the channel that the passive metrics did not register. This suggests that checking whether communication really emerged, and auditing connected-driving systems, should test the binding between message and behaviour directly rather than rely on measured informativeness alone.

This dissertation is structured as follows. The related work chapter highlights prominent studies in the literature and positions our approach within this body of work. The methodology chapter sets out the formulation and the evaluation protocol, the results chapter presents these findings, and the discussion chapter reads them through the game theory of signalling and convention.
