== Signalling Games

The foundational framework for this thesis is the signalling game. In a signalling game, an informed sender observes a private type and emits a costless message. An uninformed receiver then updates beliefs via Bayes' rule and responds accordingly @crawford1982strategic. The central result is that cheap-talk channels admit a continuum of equilibria. At one end is fully separating, where different types send different messages and communication is informative; at the other is pooling, where all types converge on one message and the channel carries no information. Which regime arises depends on the alignment of sender and receiver interests: greater misalignment produces coarser partitions.

In earlier work, @spence1973job established that signal costs break this indeterminacy. When types bear different costs for the same signal, honest separation becomes the best strategy. It motivates the design of the execution-profile signal space used in this thesis. Each profile modifies the kinematic envelope of a driving action in ways that trade off differently against the reward components of cautious versus assertive types. As a result, it provides structural cost asymmetry without pre-assigning semantic content. @fudenberg1991game supplies the solution concept Perfect Bayesian Equilibrium (PBE), which serves as the formal reference point. This thesis makes no claim to find a PBE analytically; it uses the separating/partial-pooling/pooling taxonomy as a diagnostic language for characterising what MARL training actually produces.

== Game-Theoretic Lane-Changing Models

A body of work applies signalling and game-theoretic methods directly to highway lane-changing. @shao2020discretionary cast discretionary lane-changing as a signalling game between heterogeneous drivers and solved for equilibria analytically under explicit payoff tables, showing that heterogeneous populations produce partial-pooling outcomes under realistic preference misalignment. @ali2019game and @talebpour2015modeling modelled mandatory lane changes as strategic games in connected-vehicle environments, demonstrating that accounting for driver heterogeneity improves prediction and reduces conflicts. @zhang2022game developed a game-theoretic model predictive controller that estimates merge-opponent aggressiveness in real time. At the human-AV interface, @fox2018when analysed the pedestrian-crossing encounter as a chicken game, and @risto2017human documented how road users read vehicle movement gestures as implicit type signals.

These works share a limitation relative to the present thesis: they solve analytically for equilibria under assumed payoffs, or they hand-specify the signal space and its mapping to behaviour. None train agents to discover whether a useful convention emerges at all from uninterpreted interaction over a vocabulary whose semantics are deliberately left open. This thesis closes that gap by providing both the experimental setup and the measurement analysis to answer that question empirically.

== Behavioural Type Inference

The standard approach to heterogeneity in autonomous driving is passive inference. Agents observe neighbour kinematics, build a belief over type, and plan accordingly. @bai2015intention formulated an intention-aware Partially Observable Markov Decision Process (POMDP) where the planner marginalises over discrete intent hypotheses. @zhou2018joint estimated multi-policy behaviour distributions for receding-horizon trajectory planning. @ma2021reinforcement coupled latent-type inference to the RL objective rather than treating it as a separate supervised step, learning an encoder whose representations are shaped by downstream reward.

More recent work pushes towards richer encoders. @liu2022learning trained an unsupervised driver-trait inference module at intersections and showed that conditioning on the inferred trait significantly improves collision avoidance. @liu2024automatic integrated a VAE-GRU style inference network into a Lyapunov-based SAC planner, demonstrating that explicit type conditioning reduces collision rates in complex traffic.

All these approaches frame the problem one-sidedly: the ego-vehicle asks "what is my neighbour?" but not "what does my neighbour think I am, and is my behaviour shaping that belief?" A driver aware that others are reading its kinematics can exploit that fact by choosing how to manoeuvre to convey information. @wang2020driver showed that human driving already carries type-revealing kinematic structure even when no explicit signalling is intended, suggesting that the informational substrate for emergent signalling exists in ordinary driving. @risto2017human further documented that human road users actively read and produce movement gestures to coordinate. The present thesis asks whether MARL agents, given a discrete signal channel, learn to exploit that substrate deliberately.

== Emergent Communication in MAS

Whether communication arises spontaneously from agent interaction has been studied extensively in the literature. @foerster2016learning demonstrated that agents can learn to use a discrete communication channel end-to-end via differentiable inter-agent communication. @sukhbaatar2016learning showed that continuous message passing through shared network layers supports coordination without any hand-designed protocol. @lazaridou2020emergent surveyed a decade of results in referential games, establishing that agents reliably develop shared symbol-meaning mappings when the communication channel is informative for the task reward.

Two methodological results directly shape the evaluation design of this dissertation. @eccles2019biases showed that agents frequently converge to pooling even when a communication channel is available. This happens unless training explicitly encourages two properties: positive signalling (diverse messages across situations) and positive listening (behaviour change in response to received messages). @lowe2019pitfalls surveyed some metrics to evaluate the emergent communication: Speaker Consistency - a measurement of positive signalling and Causal Influence of Communication - a measurement of causal effect of one agent's message on another agent's behavior.
